name: Daily GPS Update and Deploy to Shinyapps.io

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  update-gps-data:
    runs-on: ubuntu-latest
    steps:
      # step 1: check out your repository
      - name: Check out repo
        uses: actions/checkout@v3

      # step 2: install system dependencies for move package
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev

      # step 3: set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # step 4: install required R packages
      - name: Install R packages
        run: Rscript -e 'install.packages(c("cronR", "move", "dplyr", "purrr", "data.table", "zoo", "lubridate"), repos="https://cloud.r-project.org")'

      # step 5: run R scripts to update location data
      - name: Run location_data.R
        run: Rscript location_data.R
        
      - name: Run filter_location_data.R for Donana
        run: Rscript Donana_flooding/filter_location_data.R

      - name: Run filter_location_data.R for GPI
        run: Rscript GPI/filter_location_data.R
        
      - name: Run filter_location_data.R for Senegal Delta
        run: Rscript Senegal_delta/filter_location_data.R

      # step 6: deploy app to shinyapps.io
      - name: Deploy to shinyapps.io
        run: |
          install.packages("rsconnect")
          library(rsconnect)
          rsconnect::setAccountInfo(name = Sys.getenv("SHINYAPPS_ACCOUNT"),
                                    token = Sys.getenv("SHINYAPPS_TOKEN"),
                                    secret = Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp(appDir = ".", forceUpdate = TRUE)
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
