name: Weekly GPS Update and Deploy to Shinyapps.io

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs once a week, every Monday at midnight UTC
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  update-gps-data:
    runs-on: ubuntu-20.04  # Use stable OS

    steps:
      # step 1: check out repository
      - name: Check out repo
        uses: actions/checkout@v3

      # step 2: install system dependencies for move, sf, and Quarto
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj-dev libgeos-dev libudunits2-dev gdal-bin
          wget -qO- https://quarto.org/download/latest/quarto-linux-amd64.deb > quarto.deb
          sudo dpkg -i quarto.deb

      # step 3: set up latest supported R version from ShinyApps.io
      - name: Set up R
        run: |
          # Get latest supported R version from ShinyApps.io
          SUPPORTED_R=$(Rscript -e 'versions <- rsconnect::showVersions("shinyapps.io"); cat(max(versions$r_version))')

          echo "Using R version $SUPPORTED_R"
          
          # Install the supported R version
          sudo apt-get update
          sudo apt-get install -y r-base=$SUPPORTED_R-1

      # step 4: install required R packages dynamically
      - name: Install R packages
        run: Rscript -e "install.packages(c('rnaturalearthdata','rnaturalearth','shiny','sf', 'cronR', 'move', 'dplyr', 'purrr', 'data.table', 'zoo', 'lubridate', 'mapview', 's2', 'rsconnect','leaflet','leaflet.extras','leafgl','terra','ggplot2'), repos='https://cloud.r-project.org')"

      # step 5: run R scripts to update location data
      - name: Run location_data.R
        run: Rscript location_data.R

      - name: Run filter_location_data.R for Donana
        run: Rscript Donana_flooding/filter_location_data.R

      - name: Run filter_location_data.R for GPI
        run: Rscript GPI/filter_location_data.R

      - name: Run filter_location_data.R for Senegal Delta
        run: Rscript Senegal_delta/filter_location_data.R

      # step 6: check R environment before deployment
      - name: Check R environment
        run: Rscript -e "sessionInfo()"

      # step 7: deploy each app separately
      - name: Deploy Donana_flooding app to shinyapps.io
        run: |
          Rscript -e "install.packages('rsconnect', repos='https://cloud.r-project.org')"
          Rscript -e "library(rsconnect);
                      rsconnect::setAccountInfo(name = '${{ secrets.SHINYAPPS_ACCOUNT }}',
                                                token = '${{ secrets.SHINYAPPS_TOKEN }}',
                                                secret = '${{ secrets.SHINYAPPS_SECRET }}');
                      rsconnect::deployApp(appDir = 'Donana_flooding', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      - name: Deploy GPI app to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::deployApp(appDir = 'GPI', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      - name: Deploy Senegal_delta app to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::deployApp(appDir = 'Senegal_delta', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}

      - name: Deploy Summary_stats app to shinyapps.io
        run: |
          Rscript -e "library(rsconnect);
                      rsconnect::deployApp(appDir = 'Summary_stats', forceUpdate = TRUE)"
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
